version: '3.8'

services:
  form-service:
    build: .
    container_name: form-service
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=development-key
      - DATABASE_URL=sqlite:///instance/submissions.db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    networks:
      - app-network
      - poc-portal-network

# Create the instance volume directory if it doesn't exist
volumes:
  instance:
    driver: local

networks:
  app-network:
    driver: bridge
  poc-portal-network:
    external: true
    name: poc-portal_app-network 