version: '3.8'

services:
  form-service:
    build: .
    container_name: form-service
    user: root
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=development-key
      - STORAGE_DIR=/app/instance
      - APPLICATION_ROOT=/
    volumes:
      - storage_data:/app/instance
    restart: unless-stopped
    networks:
      - app-network
      - poc-portal-network

# Named volumes for persistence
volumes:
  storage_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/instance
      o: bind

networks:
  app-network:
    driver: bridge
  poc-portal-network:
    external: true
    name: poc-portal_app-network 